name: json_serializable_plus
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
#   path: ^1.8.0
  build: ^2.3.1
  json_annotation_plus:
    git: https://github.com/irwan75/json_annotation_plus.git
  # json_annotation_plus:
    # path: ../json_annotation_plus  
  source_gen: ^1.2.5

# dev_dependencies:
  # lints: ^2.0.0
  # test: ^1.16.0
