name: json_serializable_plus
description: A starting point for Dart libraries or applications.
version: 1.1.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
#   path: ^1.8.0
  build: ">=2.3.1 <2.4.1"
  json_annotation_plus:
    git: 
      url: https://github.com/irwan75/json_annotation_plus.git
      ref: 1.1.0
  # json_annotation_plus:
  #   path: ../json_annotation_plus  
  source_gen: ">=1.2.7 <1.3.3"

# dev_dependencies:
  # lints: ^2.0.0
  # test: ^1.16.0
